#!/usr/bin/env node
/*
 * Embeds verse_database/muhurta/ into jyotish_calculator.html.
 *
 * Why this exists: the app is normally opened as a local file, and browsers
 * block fetch() on file:// URLs. loadMuhurtaDB() still tries the JSON files
 * first — so editing a rule and reloading over http:// takes effect at once —
 * and falls back to the block this script writes.
 *
 * The JSON files are the single source of truth. Run after every rule change:
 *     node tools/build_muhurta_inline.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DB = path.join(ROOT, 'verse_database', 'muhurta');
const HTML = path.join(ROOT, 'jyotish_calculator.html');

const BEGIN = '/* MUHURTA_DB_INLINE:BEGIN';
const END = '/* MUHURTA_DB_INLINE:END */';

const TABLES = ['mc_tithi.json','mc_nakshatra.json','mc_yoga.json','mc_karana.json',
  'mc_vara.json','mc_tarabala.json','mc_chandrabala.json','mc_graha.json',
  'mc_prohibited.json','mc_festival.json','mc_biological.json'];
const PROFILES = ['garbhadhana'];

const bundle = { tables: {}, profiles: {}, builtAt: new Date().toISOString().slice(0, 10) };
let rules = 0;

for (const f of TABLES) {
  const j = JSON.parse(fs.readFileSync(path.join(DB, f), 'utf8'));
  bundle.tables[f] = j;
  rules += j.rules.length;
}
for (const p of PROFILES) {
  bundle.profiles[p] = JSON.parse(fs.readFileSync(path.join(DB, 'profiles', p + '.json'), 'utf8'));
}

/* JSON.stringify then escape the two sequences that would break out of a
   <script> block or terminate the surrounding comment. */
const json = JSON.stringify(bundle)
  .replace(/<\/script>/gi, '<\\/script>')
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029');

const block =
`${BEGIN} — generated by tools/build_muhurta_inline.js from
   verse_database/muhurta/. Do not edit by hand: edit the JSON, then re-run
   \`node tools/build_muhurta_inline.js\`. The JSON files stay the single source
   of truth; this copy exists only so the module works over file://.
   ${TABLES.length} tables · ${PROFILES.length} profile(s) · ${rules} rules · built ${bundle.builtAt} */
var MUHURTA_DB_INLINE=${json};
${END}`;

let html = fs.readFileSync(HTML, 'utf8');
const a = html.indexOf(BEGIN);
const b = html.indexOf(END);
if (a < 0 || b < 0 || b < a) {
  console.error('Markers not found in jyotish_calculator.html — aborting without writing.');
  process.exit(1);
}
html = html.slice(0, a) + block + html.slice(b + END.length);
fs.writeFileSync(HTML, html);

console.log('Embedded ' + TABLES.length + ' tables, ' + PROFILES.length + ' profile(s), '
  + rules + ' rules (' + (json.length / 1024).toFixed(1) + ' KB) into jyotish_calculator.html');
